version: '3.6'

services:
    web:
        container_name: web
        build:
            dockerfile: .docker/nginx/Dockerfile
        depends_on:
            - php-fpm81
        volumes:
            - .:/var/www:rw,cached
            - ./var:/var/www/var:rw
            - ./public:/var/www/public:rw,delegated
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        networks:
            - internal

    php-fpm81:
        image: php-fpm:8.1
        build:
            dockerfile: .docker/php/Dockerfile
        container_name: php-fpm81
        volumes:
            - .:/var/www:rw,cached
            - ./var:/var/www/var:rw
            - ./public:/var/www/public:rw,delegated
        ports:
            - 7788:7788
            - 7790:7790
        networks:
            - internal


    nodejs:
        container_name: nodejs
        build:
            context: .
            target: nodejs
        depends_on:
            - web
        environment:
            WEB_HOST: resume-creater
            WEB_PORT: 80
        volumes:
            - .:/srv/www:rw,cached
            - ./public:/srv/www/public:rw,delegated
        ports:
            - "35729:35729"

networks:
    internal:
        driver: bridge
