version: '3.6'

services:
    web:
        container_name: web-resume
        build:
            dockerfile: .docker/nginx/Dockerfile
        image: nginx:latest
        ports:
            - "80:80"



#
#    web:
#        container_name: web
#        hostname: resume-creater
#        build:
#            context: .
#            target: web-app
#            args:
#                XDEBUG: 1
#        environment:
#          XDEBUG_CONFIG: "client_host=192.168.115.1"
#          # App environment
#          APP_ENV: dev
#        volumes:
#          - .:/srv/www:rw,cached
#          - ./var:/srv/www/var:rw
#          - ./public:/srv/www/public:rw,delegated
#        ports:
#          - "8088:80"
#
#    nodejs:
#        container_name: nodejs
#        build:
#            context: .
#            target: nodejs
#        depends_on:
#            - web
#        environment:
#            WEB_HOST: resume-creater
#            WEB_PORT: 80
#        volumes:
#            - .:/srv/www:rw,cached
#            - ./public:/srv/www/public:rw,delegated
#        ports:
#            - "35729:35729"
#    app:
#        container_name: php
#        build:
#            target: php-web
